---
title: "Prostate Path Parsing"
subtitle: "Comparison of Output"
author: "Data Date: 2017-10-15"
date: "Report Date: `r Sys.Date()`"
output: 
  tufterhandout::html_tufte_handout:
        theme: cosmo
        toc: true
        toc_float: true
        toc_depth: 2
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F, fig.width = 12, cache = F)
```


```{r}
# load packages
library(dplyr)
library(tidyr)
library(knitr)
library(pander)
library(stargazer)
library(DT)


# load data
load(file="data/tidy/pp.rda")

# Create empty list to hold results
r <- list()

# Define the variables for which I want to do comparisons
vars <- c("glcombined", 
          "pathmgnpos", "pathecepos", "pathsvipos", 
          "pathnodes_dissected", "pathnodes_positive", "pathnodes_status",
          "tstagep", "nstagep")
```


```{r functions}
# Function to compare 2 data types against each other
compare2 <- function(x, y, varname) {
  # x is the first data source that will be used in the comparison
  # y is the first data source that will be used in the comparison
  # varname represents variables to compare
  x_compare <- paste0(x,"_",varname)
  y_compare <- paste0(y,"_",varname)
  
  total <- sum(!is.na(pp[,x_compare] == pp[,y_compare]))
  correct <- sum(pp[,x_compare] == pp[,y_compare], na.rm=T)

  result <- c(
    sprintf("%.0f",total), 
    sprintf("%.1f%%", (correct/total)*100)
  )
  m <- matrix(result, 1, 2)
  colnames(m) <- c(paste(x,"vs.", y, "(n)"),paste(x,"vs.", y, "(%)"))
  rownames(m) <- varname
  return(m)
}

# Function to compare all 3 data types against each other
compare3 <- function(varname) {
  # y represents variables to compare
  p_compare <- paste0("p_",varname)
  s_compare <- paste0("s_",varname)
  u_compare <- paste0("u_",varname)
  total <- sum(!is.na(pp[,u_compare]) & !is.na(pp[,s_compare]) & !is.na(pp[,p_compare]))
  correct <- sum(pp[,u_compare] == pp[,s_compare] & pp[,u_compare] == pp[,p_compare], na.rm = T)
  result <- c(
    sprintf("%.0f",total), 
    sprintf("%.1f%%", (correct/total)*100)
  )
  m <- matrix(result, 1, 2)
  colnames(m) <- c("All 3 (n)","All 3 (%)")
  rownames(m) <- varname
  return(m)
}

# Functiomn to make wide table of comparisons
allcomparisons <- function(x) {
  cbind(
    compare2("u", "p", x),
    compare2("u", "s", x),
    compare2("p", "s", x),
    compare3(x)
  )  
}

crosstables <- function(varname) {
  p_compare <- paste0("p_",varname)
  s_compare <- paste0("s_",varname)
  u_compare <- paste0("u_",varname)
  t <- list()
  t$t1 <- table(!is.na(pp[,p_compare]), !is.na(pp[,u_compare]), dnn=c("Parser", "UODB"))
  t$t2 <- table(!is.na(pp[,s_compare]), !is.na(pp[,u_compare]), dnn=c("SDE", "UODB"))
  t$t3 <- table(!is.na(pp[,s_compare]), !is.na(pp[,p_compare]), dnn=c("SDE", "Parser"))
  
  t$t4 <- table(pp[,p_compare], pp[,u_compare], dnn=c("Parser", "UODB"), useNA = "always")
  t$t5 <- table(pp[,s_compare], pp[,u_compare], dnn=c("SDE", "UODB"), useNA = "always")
  t$t6 <- table(pp[,s_compare], pp[,p_compare], dnn=c("SDE", "Parser"), useNA = "always")  
  
  return(t)
}

```
# To Do

# Available Data

- Total records: `r nrow(pp)`

## All Variables
```{r}
data.frame(
            "Variable" = colnames(pp),
            "Values Present" = apply(pp, 2, function(x) sum(!is.na(x))),
            "Data Present Percent" = apply(pp, 2, function(x) round((sum(!is.na(x))/nrow(pp))*100,2)),
            row.names = NULL
            ) %>% datatable()
```

# All Comparisons
```{r}


t <- lapply(vars, allcomparisons)
t <- do.call(rbind, t)

kable(t)
```

# Gleason
```{r}
glreport <- data.frame(
  Category = c(
    "Complete cases from UODB", 
    "Complete cases from SDE",
    "Complete cases from Parser",
    "Complete cases from UODB and SDE",
    "Complete cases from UODB and Parser",
    "Complete cases from UODB, SDE, Parser"
  ),
  Gleason = c(
    sum(!is.na(pp$u_glcombined)),
    sum(!is.na(pp$s_glcombined)),
    sum(!is.na(pp$p_glcombined)),
    sum(!is.na(pp$u_glcombined) & !is.na(pp$s_glcombined)),
    sum(!is.na(pp$u_glcombined) & !is.na(pp$p_glcombined)),
    sum(!is.na(pp$u_glcombined) & !is.na(pp$s_glcombined) & !is.na(pp$p_glcombined))
  )
)

kable(glreport)

crosstables("glcombined")
```

# T Stage
```{r}
crosstables("tstagep")
```

# N Stage
```{r}
crosstables("tstagep")
```

# Path Margin Positive
```{r}
crosstables("pathmgnpos")
```

# Path ECE Positive
```{r}
crosstables("pathecepos")
```

# Path SVI Positive
```{r}
crosstables("pathsvipos")
```

# Path Nodes Positive
```{r}
crosstables("pathnodes_positive")
```

# Path Nodes Dissected
```{r}
crosstables("pathnodes_dissected")
```
